apiVersion: v1
kind: Service
metadata:
  name: {{ application_name }}-app
  namespace: {{ namespace_name }}
  labels:
    app: {{ application_name }}-app
    app.kuberentes.io/version: {{ version }}

spec:
  selector:
    app: {{ application_name }}-app
    version: {{ version }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

