# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mydata
  labels:
    app: mysql

spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306

---
# Client service for connecting to any MySQL instance for reads.
# # For writes, you must instead connect to the primary: mysql-0.mysql.

apiVersion: v1
kind: Service
metadata: 
  name: mysql-read
  namespace: mydata

spec:
  type: ClusterIP
  selector: 
    app: mysql
  ports:
  - name: mysql
    port: 3306
