apiVersion: v1
kind: Service
metadata:
  name: mydata-backend-app
  namespace: mydata
  lables:
    app: mydata-backend-app
    app.kuberentes.io/version: v.1.0

spec:
  selector:
    app: mydata-backend-app
    version: v.1.0
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

